### ISSUE TITLE
Signing txObject vs. keccak(EthAddress)

### ISSUE THREAD

**Issue by lucashenning** [wshbair/HSM2ETH#1]
Hi @wshbair, thank you for publishing this, your code has helped me a lot implementing AWS KMS based Ethereum signing. I really appreciate it. :+1: 

After days of messing with the ASN1 encoding and identifying the right r,s,v values to get on the "good" side of the curve, it's finally working.

Question for you, **don't you need to sign the final Tx Object?** 

On line 52 of your script, you're signing the **EthAddress** of your account. 
https://github.com/wshbair/HSM2ETH/blob/94292e726fbc8a6df2ba01c7c9111a9e657679a2/main.js#L51-L52

On lines 106 and 107, you're not signing the transaction object itself. You're still using the `r` and `s` values from the original signature that was generated by signing the eth address. 
https://github.com/wshbair/HSM2ETH/blob/94292e726fbc8a6df2ba01c7c9111a9e657679a2/main.js#L96-L109

I'm doing the same thing in my script but the transaction won't go through if I'm not signing the actual transaction object again, i.e. if I'm using the initial values of `r` and `s` the transaction will fail. That's why I'm signing the actual transaction object again (see code below, you can see 2 signatures being generated). 

```js
    let ethAddrHash = ethutil.keccak(Buffer.from(ethAddr));
    
    // signing the 1st time
    // we're signing the hash of our ethereum address
    let sig = await findEthereumSig(ethAddrHash);
    let recoveredPubAddr = findRightKey(ethAddrHash, sig.r, sig.s, ethAddr);

    const txParams: TxData = {
        nonce: await web3.eth.getTransactionCount(ethAddr),
        gasPrice: '0x0918400000',
        gasLimit: 160000,
        to: '0x0000000000000000000000000000000000000000',
        value: '0x00',
        data: '0x00',
        r: sig.r.toBuffer(), // using r from the first signature
        s: sig.s.toBuffer(), // using s from the first signature
        v: recoveredPubAddr.v
    }

    console.log(txParams);

    const tx = new Transaction(txParams, {
        chain: 'kovan',
    });

    // signing the 2nd time
    // this time we're signing the hash of the actual transaction
    let txHash = tx.hash(false);
    sig = await findEthereumSig(txHash);
    recoveredPubAddr = findRightKey(txHash, sig.r, sig.s, ethAddr);
    tx.r = sig.r.toBuffer(); // replacing r based on 2nd sig
    tx.s = sig.s.toBuffer(); // replacing s based on 2nd sig
    tx.v = new BN(recoveredPubAddr.v).toBuffer();
    console.log(tx.getSenderAddress().toString('hex'));

    // Send signed tx to ethereum network 
    const serializedTx = tx.serialize().toString('hex');    
    web3.eth.sendSignedTransaction('0x' + serializedTx)
```

I was wondering if you have found a way to avoid the second signature. Since building the sig is a tedious process, I'd like to run it only once.

One more thing, if you want to avoid the `while` loop, you can use the inverted value of `s` to be on the good side of the curve. (I used BN instead of BigNumber) Code:

```js
    let secp256k1N = new BN("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", 16); // max value on the curve
    let secp256k1halfN = secp256k1N.div(new BN(2)); // half of the curve
    // Because of EIP-2 not all elliptic curve signatures are accepted
    // the value of s needs to be SMALLER than half of the curve
    // i.e. we need to flip s if it's greater than half of the curve
    if (s.gt(secp256k1halfN)) {
        console.log("s is on the wrong side of the curve... flipping - tempsig: " + tempsig + " length: " + tempsig.length);
        // According to EIP2 https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md
        // if s < half the curve we need to invert it 
        // s = curve.n - s
        s = secp256k1N.sub(s);
        console.log("new s: " + s.toString(10));
        return { r, s }
    }
    // if s is less than half of the curve, we're on the "good" side of the curve, we can just return
    return { r, s }
```

Thanks again for your code. It was fun implementing this based on your flow.

**Comment by wshbair** [comment]
Hello, sorry for being quit late in my response,  

Thanks for your interest in the code, based on my understanding there is no need for the second signing. The idea here is with the first sign of the Ethereum address the Tx validator need to check if the transaction is coming from the real source address. So it will extract the r and s value in the claimed Tx and check if it can recover the public key from the signature.  If the recovered public key is the same as the one in the To field of the transaction then the Tx is valid. 

I have tried it and the only error I got that the "Error: Returned error: insufficient funds for gas * price + value" which means the transaction is valid but the claimed address is out of gas. 

Hope my answer will help

**Comment by wshbair** [comment]
Thanks a lot it, your approach perfectly fixed that, I will fix my code accordingly. 
I was trying to avoid the first signature, but it does not work, which means we need two signing process; one for the address and the second for the txObject.

The link for the transaction on Rinkeby testnet
https://rinkeby.etherscan.io/tx/0x538a61664c99431c160232a53c9907898d005464a4c5eed3100fdc0763b12f01
