### ISSUE TITLE
is there any way to get private key from HSM

### ISSUE THREAD

**Issue by cliff0412** [wshbair/HSM2ETH#2]
the code only shows generate key pairs, is there any way to get the key from HSM.

**Comment by wshbair** [comment]
The concept of HSM is built around keeping the private key inside the HSM device for security reasons. 
Still, I read some posts about this option in the older version of SoftHSM library

**Comment by bitcoinbrisbane** [comment]
What @wshbair said, the HSM purpose is to never reveal the private key.

**Comment by cliff0412** [comment]
as specified in PKCS11, there is an option called extractable, if this is set true during generating keys, the key should be extractable. maybe there should be a command line tool to extract the private key.
