### ISSUE TITLE
getting Segmentation fault during signing

### ISSUE THREAD

**Issue by cliff0412** [wshbair/HSM2ETH#3]
getting error Segmentation fault when invoking sign.once(msgHash)

**Comment by wshbair** [comment]
Hello, 
Sorry for the late response, 
I have just pushed a completely a new working demo with the function of generating, signing, and TX builder. 
Please have a look and happy to get your feedback 
regards,

**Comment by cliff0412** [comment]
thanks for your reply. i have figured out the solution already.
